# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bisquare_call <- function(h1, h2, delta, r, A) {
    .Call('bicon_bisquare_call', PACKAGE = 'bicon', h1, h2, delta, r, A)
}

covMat1_call <- function(h, var, kappa) {
    .Call('bicon_covMat1_call', PACKAGE = 'bicon', h, var, kappa)
}

covMat3_call <- function(h, var, kappa) {
    .Call('bicon_covMat3_call', PACKAGE = 'bicon', h, var, kappa)
}

